services:

# adds top_menu_event to KevinPapst\AdminLTEBundle\Menu\MenuBuilder:
  Survos\BaseBundle\Menu\MenuBuilder:
    class: Survos\BaseBundle\Menu\MenuBuilder
    arguments:
      - "@knp_menu.factory"
      - "@event_dispatcher"
    tags:
      - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: survos_sidebar_menu }
      - { name: knp_menu.menu_builder, method: createPageMenu, alias: survos_page_menu }